// This is a part of the Hangil IT Program Source.
// Copyright (C) 1998- (c) Hangil IT Corporation
// All rights reserved.
//

//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by APlateUI.rc
// resource boundaru : 3501 ~ 3799
//  control boundary : 3800 ~ 4000
#define	IDD_OPTIONPAGE_WELDMAP		3501
#define	IDD_OPTIONPAGE_VBRACING		3502
#define	IDD_OPTIONPAGE_TUGIRDER		3503
#define	IDD_OPTIONPAGE_TENDON		3504
#define	IDD_OPTIONPAGE_SUMMARY		3505
#define	IDD_OPTIONPAGE_SPLICE		3506
#define	IDD_OPTIONPAGE_SLABGEN		3507
#define	IDD_OPTIONPAGE_SHOE			3508
#define	IDD_OPTIONPAGE_PLATECROSSBEAM	3509
#define	IDD_OPTIONPAGE_PLANGEN		3510
#define	IDD_OPTIONPAGE_PAINT		3511
#define	IDD_OPTIONPAGE_LINEINFO		3512
#define	IDD_OPTIONPAGE_HBRACING		3513
#define	IDD_OPTIONPAGE_GENERAL_DIM	3514
#define	IDD_OPTIONPAGE_GENERAL		3515
#define	IDD_OPTIONPAGE_ETCDETAIL	3516
#define	IDD_OPTIONPAGE_DETAIL_DIM	3517
#define	IDD_OPTIONPAGE_DETAIL		3518
#define	IDD_OPTIONPAGE_DECKREBAR	3519
#define	IDD_OPTIONPAGE_CAMBER		3520
#define	IDD_OPTIONPAGE_BM			3521
#define	IDD_OPTIONPAGE_APLATEGEN	3522
#define	IDB_RADIOON					3523
#define	IDB_RADIOOFF				3524
#define	IDB_ITEMS					3525
#define	IDB_CHECKON					3526
#define	IDB_CHECKOFF				3527
#define	IDC_OPTION_TREE_RIGHT		3800
#define	IDC_OPTION_TREE_LEFT		3801
#define	IDC_OPTION_TREE				3802
#define	IDC_GRID2_UI				3803
#define	IDC_GRID1_UI				3804
#define	IDC_GRID_UI					3805
#define	ID_PLATEOPT_SAVEBUTTON		5018
#define	ID_PLATEOPT_LOADBUTTON		5017
#define	ID_PLATEOPT_DEFAULTBUTTON	5019


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3528
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3806
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
