//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by APlateOutBM.rc
// resource boundaru : 2501 ~ 2799
//  control boundary : 2800 ~ 3000

#define	IDD_DIALOG_APLATE_WELD_CHANGE	2501
#define	IDD_DIALOG_APLATE_OUTBM			2502
#define	IDD_DIALOG_APLATE_NONDES		2503
#define	IDB_CHECKON_BM					2504
#define	IDB_CHECKOFF_BM					2505
#define	IDB_BMITEMS						2506

#define	IDC_TREE_BMOUT					2800
#define	IDC_STATIC_PROGRESS				2801
#define	IDC_PROGRESS					2802
#define	IDC_BUTTON_WELD_OUT				2803
#define	IDC_BUTTON_WELD_FILE_OPEN		2804
#define	IDC_BUTTON_WELD_CHANGE_OUT		2805
#define	IDC_BUTTON_WELD_CHANGE_FILE_OPEN	2806
#define	IDC_BUTTON_OPEN_DOMYUN			2807
#define	IDC_BUTTON_NONDES_OUT			2808
#define	IDC_BUTTON_NONDES_FILE_OPEN		2809
#define	IDC_BUTTON_BMOUT				2810
#define	IDC_BUTTON_BM_FILE_OPEN			2811
#define	IDC_BUTTON_ALL_PRINTOUT			2812
#define	IDC_BUTTON_ALL_OUTCANCEL		2813


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2507
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2814
#define _APS_NEXT_SYMED_VALUE           3000
#endif
#endif
